/* ONLY APPEND TO THIS FILE - DO NOT REORDER OR REMOVE ENTRIES */

#ifndef MARKET
#define MARKET(mic, desc)
#endif
MARKET(XNYS,NYSE)
MARKET(XNAS,NASDAQ)
MARKET(ARCX,NYSE ARCA)
MARKET(XBOS,NASDAQ OMX BX)
MARKET(XPSX,NASDAQ OMX PSX)
MARKET(BATY,BATS Y)
MARKET(BATS,BATS)
MARKET(EDGA,DIRECT EDGE A)
MARKET(EDGX,DIRECT EDGE X)
MARKET(CAES,CROSSFINDER)
