
set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "i01 project")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${I01_ROOT}/README.rst")
set(CPACK_PACKAGE_VENDOR "Ido Rosen")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}")
set(CPACK_RESOURCE_FILE_LICENSE "${I01_ROOT}/LICENSE")

# version
set(CPACK_PACKAGE_VERSION_MAJOR "${I01_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${I01_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${I01_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION "${I01_VERSION}-${I01_BUILD_VERSION}")

# binary package
set(CPACK_GENERATOR "TGZ")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")

# source package
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES
    "~$;[.]swp$;/[.]git/;.gitignore;/build/;tags;cscope.*")
set(CPACK_SOURCE_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")

include(CPack)
